image: golang:1.13

build:
  script:
    - env GOOS=linux GOARCH=amd64 go build -o maulu_linux_amd64
    - env GOOS=linux GOARCH=arm64 go build -o maulu_linux_arm
    - env GOOS=linux GOARCH=arm go build -o maulu_linux_arm64
  stage: build
  artifacts:
    paths:
      - maulu_linux_amd64
      - maulu_linux_arm
      - maulu_linux_arm64
      - LICENSE
      - README.md
      - config.json
